require 'spec_helper'
require 'active_support/core_ext/hash'
require 'services/three_sixty_api/three_sixty_api_service'
require 'savon'


class ThreeSixtyTester < Core::Command
  services :three_sixty_api
end

describe Services::ThreeSixtyApi::ThreeSixtyApiService do
  
  it 'should extract the id for the requested bean' do
    Services::ThreeSixtyApi::Session.extract_id("bus_entity_context", SOAP_RESPONSE.gsub(/\s/,"")).should == '649147c693cd6fe5177e7db894fe75e9'
  end
  
  it 'should return a hash that can be converted into an ns2:pair string' do
    pair_hash = Services::ThreeSixtyApi::Session.pair("name", "steve")
    Gyoku.xml(pair_hash).should == NS2STR.gsub(/\s/,"")
  end
  
  it 'should return a hash that can be converted into an ns2:pair array' do
    pair_hash = Services::ThreeSixtyApi::Session.pair("testArrayPair", {"name" => 'steve', "brilliance" => 'amazing', 'sport' => 'pesky'})
    Gyoku.xml(pair_hash).should == NS2ARR.gsub(/\s/,"")
  end
  
  it 'should set the client.wsdl with the endpoint and document using the config url and wsdl provided' do
    wsdl = mock
    wsdl.expects(:endpoint=).with("http://stuffandnonsense/v2")
    wsdl.expects(:document=).with("/stuff/nonsense.wsdl")
    wsdl.stubs(:request=)
    Savon::Client.any_instance.stubs(:wsdl).returns(wsdl)
    session = Services::ThreeSixtyApi::Session.new({"url" => "http://stuffandnonsense/v2"}, "/stuff/nonsense.wsdl")
    session.client
  end
  
  it 'should create the savon client only once' do
    session = Services::ThreeSixtyApi::Session.new(nil, nil) #we don't care about the wsdl or config for this test
    Savon::Client.expects(:new).once.returns(mock) #we have to return something from new or the class variable won't be populated.
    session.client
    session.client
  end
  
  it 'should call login and set the session id' do
    session = Services::ThreeSixtyApi::Session.new(nil, nil) #we don't care about the wsdl or config for this test
    session.expects(:login).returns("123abc456")
    
    session.stubs(:create)
    session.stubs(:store)
    session.stubs(:logout)
    
    session.send_to_360("test template", {:email => 'test@test', :custom_data => {'name' => 'steve'}})
    session.session_id.should == "123abc456"  
  end
  
  it 'should call ceate and store for each item in the data array' do
     session = Services::ThreeSixtyApi::Session.new(nil, nil)
     session.stubs(:login)

     session.expects(:create).with("steve1@test.co.uk", 'test template', {'name' => 'steve1'}).returns('123abc')
     session.expects(:store).with('123abc')
     session.expects(:create).with("steve2@test.co.uk", 'test template', {'name' => 'steve2'}).returns('456def')
     session.expects(:store).with('456def')
     
     session.stubs(:logout)

     session.send_to_360("test template", [{:email => 'steve1@test.co.uk', :custom_data => {'name' => 'steve1'}}, {:email => 'steve2@test.co.uk', :custom_data => {'name' => 'steve2'}}]) 
  end
  
  it 'should call logout' do
    session = Services::ThreeSixtyApi::Session.new(nil, nil)
    session.stubs(:login)    
    session.stubs(:create)
    session.stubs(:store)
    
    session.expects(:logout)
    
    session.send_to_360("test template", {:email => 'test@test', :custom_data => {'name' => 'steve'}})  
  end
  

  
end

NS2STR = <<ns2str
<n2:key>name</n2:key>
<n2:value>
  <n2:str>steve</n2:str>
</n2:value>
ns2str

NS2ARR = <<ns2arr
<n2:key>testArrayPair</n2:key>
<n2:value>
  <n2:arr>
    <n2:pairs>
      <n2:key>name</n2:key>
      <n2:value>
        <n2:str>steve</n2:str>
        </n2:value>
    </n2:pairs>
    <n2:pairs>
      <n2:key>sport</n2:key>
      <n2:value>
        <n2:str>pesky</n2:str>
      </n2:value>
    </n2:pairs>
    <n2:pairs>
      <n2:key>brilliance</n2:key>
      <n2:value>
        <n2:str>amazing</n2:str>
      </n2:value>
    </n2:pairs>
  </n2:arr>
</n2:value>
ns2arr

SOAP_RESPONSE = <<soap_response
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="urn:localhost-paint" xmlns:ns2="http://www.pure360.com/paint">
	<SOAP-ENV:Body>
		<ns1:handleRequestResponse>
			<Result>
				<ns2:pairs>
					<ns2:key>result</ns2:key>
					<ns2:value>
						<ns2:str>success</ns2:str>
					</ns2:value>
				</ns2:pairs>
				<ns2:pairs>
					<ns2:key>resultData</ns2:key>
					<ns2:value>
						<ns2:arr>
							<ns2:pairs>
								<ns2:key>bus_entity_preferencePool</ns2:key>
								<ns2:value>
									<ns2:arr>
										<ns2:pairs>
											<ns2:key>poolId</ns2:key>
											<ns2:value>
												<ns2:str>2</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>ownerType</ns2:key>
											<ns2:value>
												<ns2:str>pool</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>preference</ns2:key>
											<ns2:value>
												<ns2:arr/>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>preferenceTypeMap</ns2:key>
											<ns2:value/>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>preferenceNameMap</ns2:key>
											<ns2:value/>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>status</ns2:key>
											<ns2:value>
												<ns2:str>modified</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>beanId</ns2:key>
											<ns2:value>
												<ns2:str>busEntityPreferencePool</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>beanName</ns2:key>
											<ns2:value>
												<ns2:str>bus_entity_preferencePool</ns2:str>
											</ns2:value>
										</ns2:pairs>
									</ns2:arr>
								</ns2:value>
							</ns2:pairs>
							<ns2:pairs>
								<ns2:key>bus_entity_account_identity</ns2:key>
								<ns2:value>
									<ns2:arr>
										<ns2:pairs>
											<ns2:key>identityId</ns2:key>
											<ns2:value>
												<ns2:str>2</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>identityName</ns2:key>
											<ns2:value>
												<ns2:str>jackpot.joy</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>activeInd</ns2:key>
											<ns2:value>
												<ns2:str>Y</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>displayName</ns2:key>
											<ns2:value>
												<ns2:str>{~partner-name~}</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>forwardEmail</ns2:key>
											<ns2:value>
												<ns2:str>support@jackpotjoy.com</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>customReplyEmail</ns2:key>
											<ns2:value>
												<ns2:str>jackpotjoy@emails.jackpotjoy.com</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>customDomain</ns2:key>
											<ns2:value>
												<ns2:str>emails.jackpotjoy.com</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>dynamicReplyDomain</ns2:key>
											<ns2:value>
												<ns2:str/>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>allowInterfacesInd</ns2:key>
											<ns2:value>
												<ns2:str>Y</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>transactionalInd</ns2:key>
											<ns2:value>
												<ns2:str>N</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>passiveOptOutCount</ns2:key>
											<ns2:value>
												<ns2:str>0</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>limitReceiptActiveInd</ns2:key>
											<ns2:value>
												<ns2:str>Y</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>limitReceiptValue</ns2:key>
											<ns2:value>
												<ns2:str>1</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>listSharingLevel</ns2:key>
											<ns2:value>
												<ns2:str>SHARED</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>promoLevel</ns2:key>
											<ns2:value>
												<ns2:str>0</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>defaultLanguage</ns2:key>
											<ns2:value>
												<ns2:str>en_GB.ISO8859-15</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>replyEmail</ns2:key>
											<ns2:value>
												<ns2:str>jackpotjoy@emails.jackpotjoy.com</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>supportEmail</ns2:key>
											<ns2:value>
												<ns2:str>jackpotjoy@emails.jackpotjoy.com</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>testAddressesEmail</ns2:key>
											<ns2:value>
												<ns2:str/>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>emailTestCurrentCredit</ns2:key>
											<ns2:value>
												<ns2:str>0</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>emailTestMaxExcess</ns2:key>
											<ns2:value>
												<ns2:str>100</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>approvalRequiredInd</ns2:key>
											<ns2:value>
												<ns2:str>Y</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>approverEmails</ns2:key>
											<ns2:value>
												<ns2:arr>
													<ns2:pairs>
														<ns2:key>0</ns2:key>
														<ns2:value>
															<ns2:str>jasond@miceanddice.com</ns2:str>
														</ns2:value>
													</ns2:pairs>
												</ns2:arr>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>status</ns2:key>
											<ns2:value>
												<ns2:str>modified</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>beanId</ns2:key>
											<ns2:value>
												<ns2:str>busEntityAccountIdentity</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>beanName</ns2:key>
											<ns2:value>
												<ns2:str>bus_entity_account_identity</ns2:str>
											</ns2:value>
										</ns2:pairs>
									</ns2:arr>
								</ns2:value>
							</ns2:pairs>
							<ns2:pairs>
								<ns2:key>bus_entity_preferenceIdentity</ns2:key>
								<ns2:value>
									<ns2:arr>
										<ns2:pairs>
											<ns2:key>identityId</ns2:key>
											<ns2:value>
												<ns2:str>2</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>ownerType</ns2:key>
											<ns2:value>
												<ns2:str>identity</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>preference</ns2:key>
											<ns2:value>
												<ns2:arr>
													<ns2:pairs>
														<ns2:key>emailEdit</ns2:key>
														<ns2:value>
															<ns2:arr>
																<ns2:pairs>
																	<ns2:key>loadFromUrlHistory1</ns2:key>
																	<ns2:value>
																		<ns2:str/>
																	</ns2:value>
																</ns2:pairs>
																<ns2:pairs>
																	<ns2:key>loadFromUrlHistory2</ns2:key>
																	<ns2:value>
																		<ns2:str/>
																	</ns2:value>
																</ns2:pairs>
																<ns2:pairs>
																	<ns2:key>loadFromUrlHistory3</ns2:key>
																	<ns2:value>
																		<ns2:str/>
																	</ns2:value>
																</ns2:pairs>
																<ns2:pairs>
																	<ns2:key>loadFromUrlHistory4</ns2:key>
																	<ns2:value>
																		<ns2:str/>
																	</ns2:value>
																</ns2:pairs>
																<ns2:pairs>
																	<ns2:key>loadFromUrlHistory5</ns2:key>
																	<ns2:value>
																		<ns2:str/>
																	</ns2:value>
																</ns2:pairs>
																<ns2:pairs>
																	<ns2:key>loadFromUrlHistory6</ns2:key>
																	<ns2:value>
																		<ns2:str/>
																	</ns2:value>
																</ns2:pairs>
																<ns2:pairs>
																	<ns2:key>loadFromUrlHistory7</ns2:key>
																	<ns2:value>
																		<ns2:str/>
																	</ns2:value>
																</ns2:pairs>
																<ns2:pairs>
																	<ns2:key>loadFromUrlHistory8</ns2:key>
																	<ns2:value>
																		<ns2:str/>
																	</ns2:value>
																</ns2:pairs>
																<ns2:pairs>
																	<ns2:key>loadFromUrlHistory9</ns2:key>
																	<ns2:value>
																		<ns2:str/>
																	</ns2:value>
																</ns2:pairs>
																<ns2:pairs>
																	<ns2:key>loadFromUrlHistory10</ns2:key>
																	<ns2:value>
																		<ns2:str/>
																	</ns2:value>
																</ns2:pairs>
																<ns2:pairs>
																	<ns2:key>loadFromUrlHistory</ns2:key>
																	<ns2:value>
																		<ns2:arr>
																			<ns2:pairs>
																				<ns2:key>0</ns2:key>
																				<ns2:value>
																					<ns2:str/>
																				</ns2:value>
																			</ns2:pairs>
																			<ns2:pairs>
																				<ns2:key>1</ns2:key>
																				<ns2:value>
																					<ns2:str/>
																				</ns2:value>
																			</ns2:pairs>
																			<ns2:pairs>
																				<ns2:key>2</ns2:key>
																				<ns2:value>
																					<ns2:str/>
																				</ns2:value>
																			</ns2:pairs>
																			<ns2:pairs>
																				<ns2:key>3</ns2:key>
																				<ns2:value>
																					<ns2:str/>
																				</ns2:value>
																			</ns2:pairs>
																			<ns2:pairs>
																				<ns2:key>4</ns2:key>
																				<ns2:value>
																					<ns2:str/>
																				</ns2:value>
																			</ns2:pairs>
																			<ns2:pairs>
																				<ns2:key>5</ns2:key>
																				<ns2:value>
																					<ns2:str/>
																				</ns2:value>
																			</ns2:pairs>
																			<ns2:pairs>
																				<ns2:key>6</ns2:key>
																				<ns2:value>
																					<ns2:str/>
																				</ns2:value>
																			</ns2:pairs>
																			<ns2:pairs>
																				<ns2:key>7</ns2:key>
																				<ns2:value>
																					<ns2:str/>
																				</ns2:value>
																			</ns2:pairs>
																			<ns2:pairs>
																				<ns2:key>8</ns2:key>
																				<ns2:value>
																					<ns2:str/>
																				</ns2:value>
																			</ns2:pairs>
																			<ns2:pairs>
																				<ns2:key>9</ns2:key>
																				<ns2:value>
																					<ns2:str/>
																				</ns2:value>
																			</ns2:pairs>
																		</ns2:arr>
																	</ns2:value>
																</ns2:pairs>
															</ns2:arr>
														</ns2:value>
													</ns2:pairs>
												</ns2:arr>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>preferenceTypeMap</ns2:key>
											<ns2:value/>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>preferenceNameMap</ns2:key>
											<ns2:value/>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>status</ns2:key>
											<ns2:value>
												<ns2:str>modified</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>beanId</ns2:key>
											<ns2:value>
												<ns2:str>busEntityPreferenceIdentity</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>beanName</ns2:key>
											<ns2:value>
												<ns2:str>bus_entity_preferenceIdentity</ns2:str>
											</ns2:value>
										</ns2:pairs>
									</ns2:arr>
								</ns2:value>
							</ns2:pairs>
							<ns2:pairs>
								<ns2:key>bus_entity_context</ns2:key>
								<ns2:value>
									<ns2:arr>
										<ns2:pairs>
											<ns2:key>dbName</ns2:key>
											<ns2:value>
												<ns2:str>PUREF</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>loginId</ns2:key>
											<ns2:value>
												<ns2:str>28</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>userName</ns2:key>
											<ns2:value>
												<ns2:str>jackpotjoy.system</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>currentRoleKey</ns2:key>
											<ns2:value>
												<ns2:str>IDENT_2</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>poolId</ns2:key>
											<ns2:value>
												<ns2:str>2</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>identityId</ns2:key>
											<ns2:value>
												<ns2:str>2</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>roleList</ns2:key>
											<ns2:value>
												<ns2:arr>
													<ns2:pairs>
														<ns2:key>IDENT_2</ns2:key>
														<ns2:value>
															<ns2:str>jackpot.joy</ns2:str>
														</ns2:value>
													</ns2:pairs>
												</ns2:arr>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>isAdminLogin</ns2:key>
											<ns2:value>
												<ns2:str/>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>status</ns2:key>
											<ns2:value>
												<ns2:str>modified</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>beanId</ns2:key>
											<ns2:value>
												<ns2:str>649147c693cd6fe5177e7db894fe75e9</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>beanName</ns2:key>
											<ns2:value>
												<ns2:str>bus_entity_context</ns2:str>
											</ns2:value>
										</ns2:pairs>
									</ns2:arr>
								</ns2:value>
							</ns2:pairs>
							<ns2:pairs>
								<ns2:key>bus_entity_account_pool</ns2:key>
								<ns2:value>
									<ns2:arr>
										<ns2:pairs>
											<ns2:key>expiryDate</ns2:key>
											<ns2:value/>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>poolId</ns2:key>
											<ns2:value>
												<ns2:str>2</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>poolName</ns2:key>
											<ns2:value>
												<ns2:str>Mice and Dice Ltd Unlimited **Premier**</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>activeInd</ns2:key>
											<ns2:value>
												<ns2:str>Y</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>optOutLevel</ns2:key>
											<ns2:value>
												<ns2:str>SINGLE</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>accountType</ns2:key>
											<ns2:value>
												<ns2:str>FREE</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>emailCurrentCredit</ns2:key>
											<ns2:value>
												<ns2:str>17265679</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>emailMaxExcess</ns2:key>
											<ns2:value>
												<ns2:str>0</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>emailActiveInd</ns2:key>
											<ns2:value>
												<ns2:str>Y</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>emailPrecisionDeliveryInd</ns2:key>
											<ns2:value>
												<ns2:str>Y</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>smsCurrentCredit</ns2:key>
											<ns2:value>
												<ns2:str>346715</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>smsMaxExcess</ns2:key>
											<ns2:value>
												<ns2:str>0</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>smsActiveInd</ns2:key>
											<ns2:value>
												<ns2:str>Y</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>smsPrecisionDeliveryInd</ns2:key>
											<ns2:value>
												<ns2:str>Y</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>maxCustomFields</ns2:key>
											<ns2:value>
												<ns2:str>10</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>status</ns2:key>
											<ns2:value>
												<ns2:str>modified</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>beanId</ns2:key>
											<ns2:value>
												<ns2:str>busEntityAccountPool</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>beanName</ns2:key>
											<ns2:value>
												<ns2:str>bus_entity_account_pool</ns2:str>
											</ns2:value>
										</ns2:pairs>
									</ns2:arr>
								</ns2:value>
							</ns2:pairs>
							<ns2:pairs>
								<ns2:key>bus_entity_account_login</ns2:key>
								<ns2:value>
									<ns2:arr>
										<ns2:pairs>
											<ns2:key>lastProfileKey</ns2:key>
											<ns2:value>
												<ns2:str>IDENT_2</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>loginId</ns2:key>
											<ns2:value>
												<ns2:str>28</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>userName</ns2:key>
											<ns2:value>
												<ns2:str>jackpotjoy.system</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>activeInd</ns2:key>
											<ns2:value>
												<ns2:str>Y</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>licenceAcceptedInd</ns2:key>
											<ns2:value>
												<ns2:str>Y</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>blankTemplateAcceptedDtTm</ns2:key>
											<ns2:value>
												<ns2:str/>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>allowMultipleInd</ns2:key>
											<ns2:value>
												<ns2:str>Y</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>newDevAlertInd</ns2:key>
											<ns2:value>
												<ns2:str>N</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>newDevAlertLevel</ns2:key>
											<ns2:value>
												<ns2:str>INFO</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>lastAccessDtTm</ns2:key>
											<ns2:value>
												<ns2:str>24/01/2011 12:53</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>lastLoginDtTm</ns2:key>
											<ns2:value>
												<ns2:str>24/01/2011 12:53</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>contactEmail</ns2:key>
											<ns2:value>
												<ns2:str>jasond@miceanddice.com</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>systemLoginInd</ns2:key>
											<ns2:value>
												<ns2:str>Y</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>status</ns2:key>
											<ns2:value>
												<ns2:str>modified</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>beanId</ns2:key>
											<ns2:value>
												<ns2:str>busEntityAccountLogin</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>beanName</ns2:key>
											<ns2:value>
												<ns2:str>bus_entity_account_login</ns2:str>
											</ns2:value>
										</ns2:pairs>
									</ns2:arr>
								</ns2:value>
							</ns2:pairs>
							<ns2:pairs>
								<ns2:key>bus_entity_preferenceLogin</ns2:key>
								<ns2:value>
									<ns2:arr>
										<ns2:pairs>
											<ns2:key>loginId</ns2:key>
											<ns2:value>
												<ns2:str>28</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>ownerType</ns2:key>
											<ns2:value>
												<ns2:str>login</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>preference</ns2:key>
											<ns2:value>
												<ns2:arr>
													<ns2:pairs>
														<ns2:key>emailEdit</ns2:key>
														<ns2:value>
															<ns2:arr>
																<ns2:pairs>
																	<ns2:key>displayBody</ns2:key>
																	<ns2:value>
																		<ns2:str>html</ns2:str>
																	</ns2:value>
																</ns2:pairs>
																<ns2:pairs>
																	<ns2:key>htmlEditor</ns2:key>
																	<ns2:value>
																		<ns2:str>wysiwyg</ns2:str>
																	</ns2:value>
																</ns2:pairs>
															</ns2:arr>
														</ns2:value>
													</ns2:pairs>
													<ns2:pairs>
														<ns2:key>sidebar</ns2:key>
														<ns2:value>
															<ns2:arr>
																<ns2:pairs>
																	<ns2:key>defaultSection</ns2:key>
																	<ns2:value>
																		<ns2:str>help</ns2:str>
																	</ns2:value>
																</ns2:pairs>
															</ns2:arr>
														</ns2:value>
													</ns2:pairs>
												</ns2:arr>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>preferenceTypeMap</ns2:key>
											<ns2:value/>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>preferenceNameMap</ns2:key>
											<ns2:value/>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>status</ns2:key>
											<ns2:value>
												<ns2:str>modified</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>beanId</ns2:key>
											<ns2:value>
												<ns2:str>busEntityPreferenceLogin</ns2:str>
											</ns2:value>
										</ns2:pairs>
										<ns2:pairs>
											<ns2:key>beanName</ns2:key>
											<ns2:value>
												<ns2:str>bus_entity_preferenceLogin</ns2:str>
											</ns2:value>
										</ns2:pairs>
									</ns2:arr>
								</ns2:value>
							</ns2:pairs>
						</ns2:arr>
					</ns2:value>
				</ns2:pairs>
			</Result>
		</ns1:handleRequestResponse>
	</SOAP-ENV:Body>
</SOAP-ENV:Envelope>
soap_response